name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.19-bullseye
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: f1refly
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and Test
        env:
          TEST_FLAGS: -v
        run: make

      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
